services:
  - type: web
    name: fantazi-land
    env: node
    plan: starter
    region: frankfurt # ou oregon / ohio
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/admin/sync
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BASE44_API_URL
        sync: false
      - key: BASE44_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
