[package]
name = "di-vibez/fantazi-land"
version = "1.0.1"
description = "Fantazi-Land - Plateforme de booking et galerie pour agence d'hôtesses"
license = "MIT"
readme = "README.md"

[dependencies]
"wasmer/winterjs" = "1"

[fs]
"/src" = "."

[[command]]
name = "server"
module = "wasmer/winterjs:winterjs"
runner = "https://webc.org/runner/winterjs"

[command.annotations.wasi]
env = ["NODE_ENV=production"]
main_args = ["/src/.next/standalone/server.js"]

[command.annotations.http]
port = 3001
